package sharing.enums.user_service;

public enum AuditEventType {
    LANDLORD_REGISTERED,
    PROFILE_UPDATED,
    ZALO_UID_UPDATED,
    FCM_TOKEN_REGISTERED,
    FCM_TOKEN_REVOKED,
    STAFF_INVITED,
    STAFF_PERMISSION_REPLACED,
    STAFF_DEACTIVATED,
    ABAC_POLICY_CREATED,
    ABAC_POLICY_DELETED,
    INTERNAL_CLAIMS_READ
}
