spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:15432/user-db
    username: admin
    password: admin@123
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true

app:
  pii:
    encryption-key-base64: ${APP_PII_ENCRYPTION_KEY_BASE64:}
  internal-auth:
    enabled: false
    header-name: X-Internal-Token
    token:

server:
  port: 8091
