spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:15432/user-db
    username: admin
    password: admin@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 8091
